### ISSUE TITLE
Missing Definition of Mainstream OS in glossary

### ISSUE THREAD

**Issue by Yongbeom-Kim** [Yongbeom-Kim/pe#7]
Not too sure if this fully counts as a bug, but perhaps the Mainstream OS-es should be enumerated in Glossary.

![image.png](https://raw.githubusercontent.com/Yongbeom-Kim/pe/main/files/3928d732-80b0-435a-8c31-c988481b151e.png)

**Comment by nus-pe-script** [comment]
Your response not required for this bug as the team has accepted the bug as it is.
